language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t allstarpro/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true allstarpro/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-tutorial"
  env: "DockerTutorial-env"
  bucket_name: "elasticbeanstalk-us-east-2-468959338375"
  bucket_path: "docker-tutorial"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"