language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t allstarpro/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true allstarpro/docker-react npm run test -- --coverage